# Generated by Django 3.1 on 2021-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210924_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Token_expires_at'),
        ),
    ]
