# Generated by Django 3.1 on 2021-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210924_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token_expires_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Username'),
        ),
    ]
