# Generated by Django 3.1 on 2021-09-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(db_index=True, default='Anonymous', verbose_name='Total_price')),
                ('full_name', models.CharField(db_index=True, max_length=25, verbose_name='Full_name')),
                ('address_line1', models.CharField(db_index=True, max_length=250, verbose_name='Address_line1')),
                ('address_line2', models.CharField(db_index=True, max_length=250, verbose_name='Address_line2')),
                ('city', models.CharField(db_index=True, max_length=25, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=25, verbose_name='State')),
                ('postal_code', models.IntegerField(db_index=True, verbose_name='Postal_code')),
                ('country', models.CharField(db_index=True, max_length=25, verbose_name='Country')),
                ('telephone', models.IntegerField(db_index=True, verbose_name='Telephone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
