# Generated by Django 3.1 on 2021-10-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Address Line1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Address Line2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(db_index=True, default='United State', max_length=25, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(db_index=True, max_length=25, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(db_index=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
