# Generated by Django 3.1 on 2021-10-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('items', '0002_auto_20210927_1734'),
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
    ]
