# Generated by Django 3.1 on 2021-10-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0002_auto_20211005_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
