# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/orders/add/ HTTP/1.1
content-type: application/json
Authorization: 	609528374bc8c7479ff93671d0646a3075b1345dcd7e2995ca72875bfa6b

{
    "total_price": 99.90,
    "full_name": "test100011",
    "address_line1": "teat address",
    "address_line2": "test address2",
    "city": "test city",
    "state": "test state",
    "postal_code": "560008",
    "country": "India",
    "telephone": "67555678"
}